<Project Sdk="MSTest.Sdk/4.0.2">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WpfControls\WpfControls.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Globalization" />
    <Using Include="Tudormobile.Wpf.Controls" />
    <Using Include="Tudormobile.Wpf.Converters" />
    <Using Include="Tudormobile.Wpf.Commands" />
    <Using Include="Tudormobile.Wpf.Helpers" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.CodeCoverage" Version="18.8.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Microsoft.Testing.Extensions.TrxReport" Version="2.2.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestAdapter" Version="4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MSTest.TestFramework" Version="4.2.3" />
  </ItemGroup>

</Project>
