<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tudormobile.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>Tudormobile.Wpf.Controls</RootNamespace>
    <Product>Tudormobile WpfControls</Product>
    <Description>Tudormobile WPF Control Library</Description>
    <PackageTags>WPF;WPFControls;Tudormobile;Windows;UI</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\docs\README.md" Pack="true" PackagePath="\" />
    <InternalsVisibleTo Include="WpfControls.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Images\" />
  </ItemGroup>

</Project>